version: "3.3"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
